#
# barebox image generation Makefile for AT91 images
#

pblb-$(CONFIG_MACH_AT91SAM9X5EK) += start_at91sam9x5ek
FILE_barebox-at91sam9x5ek.img = start_at91sam9x5ek.pblb
image-$(CONFIG_MACH_AT91SAM9X5EK) += barebox-at91sam9x5ek.img

pblb-$(CONFIG_MACH_AT91SAM9263EK) += start_at91sam9263ek
FILE_barebox-at91sam9263ek.img = start_at91sam9263ek.pblb
image-$(CONFIG_MACH_AT91SAM9263EK) += barebox-at91sam9263ek.img
